TICKERS = [
    "AMZN.NE",
    "BBW",
    "BOND.TO",
    "BRK.NE",
    "DOL.TO",
    "ENB.TO",
    "EQB.TO",
    "GOOG.NE",
    "GOOGL",
    "HPS-A.TO",
    "LMN.V",
    "MA.NE",
    "META.NE",
    "MSFT",
    "MSFT.NE",
    "NFTY",
    "NVDA.NE",
    "RAND",
    "TSM",
    "UMAC",
    "UNH.NE",
    "VFV.TO",
    "WELL.TO",
    "WMT.NE",
    "XEQT.TO",
    "ZDI.TO",
]

PRICE_TICKER_MAP = {
    "AMZN": "AMZN.NE",
    "BOND": "BOND.TO",
    "BRK": "BRK.NE",
    "DOL": "DOL.TO",
    "ENB": "ENB.TO",
    "EQB": "EQB.TO",
    "GOOG": "GOOG.NE",
    "HPS.A": "HPS-A.TO",
    "LMN": "LMN.V",
    "MA": "MA.NE",
    "META": "META.NE",
    "MSFT.CDR": "MSFT.NE",
    "NVDA.CDR": "NVDA.NE",
    "UNH": "UNH.NE",
    "VFV": "VFV.TO",
    "WELL": "WELL.TO",
    "WMT": "WMT.NE",
    "XEQT": "XEQT.TO",
    "ZDI": "ZDI.TO",
}